hkyh:
  schema: 'HKYH'
  license: 'B0187H242010002'
hbyh:
  schema: 'HBYH'
  license: 'B1151H242010001' 
hbnx:
  schema: 'HBNX'
  license: 'E0001H242010001'
whrc:
  schema: 'WHRC'
  license: 'B1029H242010001'
