JGXXB: T_GX_JGXX
YGB:   T_GX_YGB
GYB:   T_GX_GYB
GWXXB: T_GX_GWXX
ZZKJQKMB: T_KJ_ZZQKM
TJKMKJDZB: T_KJ_TJKMKJ
NBKMDZB: T_KJ_NBKMKJ
GRHQCKFHZ: T_KJ_GRHCFZ
GRHQCKFHZMXJL: T_KJ_GRHCFZMX
GRDQCKFHZ: T_KJ_GRDCFZ
GRDQCKFHZMXJL: T_KJ_GRDCFZMX
DGHQCKFHZ: T_KJ_DGHCFZ
DGHQCKFHZMXJL: T_KJ_DGHCFZMX
DGDQCKFHZ: T_KJ_DGDCFZ
DGDQCKFHZMXJL: T_KJ_DGDCFZMX
NBFHZ: T_KJ_NBFZ
NBFHZMXJL: T_KJ_NBFZMX
GRXDFHZ: T_KJ_GRXFZ
GRXDFHZMXJL: T_KJ_GRXFZMX
DGXDFHZ: T_KJ_DGXFZ
DGXDFHZMXJL: T_KJ_DGXFZMX
GRJCXX: T_KH_GRJCXX
GRKHGXXX: T_KH_GRKHGXXX
DGKH: T_KH_DGKHXX
GDXX: T_KH_GDXX
GLGX: T_KH_GLGX
XDHTB: T_SJD_XDHT
XMDKXXB: T_SJD_XMDKXX
PJPMXXB: T_SJD_PJPMXX
BHYWXXB: T_SJD_BHYWXX
DGBWSXYW: T_SJD_DGBSY
MYRZYWXXB: T_SJD_MYRZYXX
YTDK: T_SJD_YTDK
WTDK: T_SJD_WTDK
GRXDYWJJ: T_SJD_GXYJJ
DGXDYWJJ: T_SJD_DXYJJ
XDYWDBHT: T_SJD_XYDHT
DBGX: T_SJD_XYDGX
XDYWZHDYW: T_SJD_XYZDYW
JJKXX: T_KP_JJKXX
CZXX: T_KP_CZXX
XYKXX: T_KP_XYKXX
XYKZHJYMXB: T_KP_XYKZJYMX
SXXX: T_XG_SXXX
DKHX: T_XG_DKHX
DKZQ: T_XG_DKZQ
XDZCZR: T_XG_XDZCZR
ZCZRGXB: T_XG_ZZRGX
DKWJXTBD: T_XG_DKWXB
DHJCB: T_XG_DHJCB
JYLS: T_JL_JYLS
ZCFZKMTJB: T_ZFSN_ZFKTJ
SNTJB: T_ZFSN_SNTJ
KHJBXXB: T_KFX_KHJBXX
GDJGLQYQKB: T_KFX_GDJGL
DKMX: T_KFX_DKMX
BWYWMX: T_KFX_BWYWMX
