-- 此 CLP 文件是使用 DB2LOOK 版本 "9.5" 创建的 
-- 时间戳记: 2013-3-7 10:56:46
-- 数据库名称: EASTANSY       
-- 数据库管理器版本: DB2/AIX64 Version 9.5.4       
-- 数据库代码页: 1386
-- 数据库整理顺序为: UNIQUE




------------------------------------
-- BUFFERPOOLS 的 DDL 语句 --
------------------------------------
 
CREATE BUFFERPOOL "EAST16KPOOL"  SIZE AUTOMATIC PAGESIZE 16384;

CREATE BUFFERPOOL "EAST32KPOOL"  SIZE AUTOMATIC PAGESIZE 32768;

CREATE BUFFERPOOL "USER32KPOOL"  SIZE AUTOMATIC PAGESIZE 32768;


------------------------------------
-- TABLESPACES 的 DDL 语句 --
------------------------------------

CREATE LARGE TABLESPACE "EASTSS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST32KPOOL
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;

CREATE LARGE TABLESPACE "EASTSSI" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 16384 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 16
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST16KPOOL
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;
CREATE LARGE TABLESPACE "EASTRUNDATA" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 16
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST32KPOOL
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;

CREATE USER TEMPORARY TABLESPACE "TMPSPACE1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL USER32KPOOL
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF;


CREATE TEMPORARY TABLESPACE "TEMPSPACE2" IN DATABASE PARTITION GROUP IBMTEMPGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL USER32KPOOL
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF;


CREATE USER TEMPORARY TABLESPACE "SYSTOOLSTMPSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF;


CREATE LARGE TABLESPACE "SYSTOOLSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


-- 模拟表空间

ALTER TABLESPACE SYSCATSPACE
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000;


ALTER TABLESPACE TEMPSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      FILE SYSTEM CACHING 
      TRANSFERRATE 0.060000;


ALTER TABLESPACE USERSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000;




------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."D_EVENTLOG"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."D_EVENTLOG"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "OPERATE_TIME" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "EVENT_SOURCE" VARCHAR(100) WITH DEFAULT '' , 
		  "IP_ADDRESS" VARCHAR(100) WITH DEFAULT '' , 
		  "REMARK" VARCHAR(1024) WITH DEFAULT '' , 
		  "USER_ID" VARCHAR(50) , 
		  "DEPT_ID" VARCHAR(50) WITH DEFAULT '' )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."D_EVENTLOG"

ALTER TABLE "EASTANSY"."D_EVENTLOG" 
	ADD CONSTRAINT "PK_D_EVENTLOG" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."D_EVENTLOG"

CREATE INDEX "EASTANSY"."I_D_EVENTLOG_1" ON "EASTANSY"."D_EVENTLOG" 
		("USER_ID" ASC,
		 "DEPT_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."D_EVENTLOG"

CREATE INDEX "EASTANSY"."I_D_EVENTLOG_2" ON "EASTANSY"."D_EVENTLOG" 
		("OPERATE_TIME" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."D_TASK_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."D_TASK_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SERVER_ID" VARCHAR(100) , 
		  "USER_ID" VARCHAR(50) , 
		  "USER_NAME" VARCHAR(100) , 
		  "CREATE_TIME" TIMESTAMP , 
		  "RUN_STATE" VARCHAR(1) , 
		  "START_TIME" TIMESTAMP , 
		  "END_TIME" TIMESTAMP , 
		  "RUN_TYPE" VARCHAR(1) , 
		  "MODEL_NAME" VARCHAR(500) , 
		  "SERVER_SHOWNAME" VARCHAR(1000) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."D_TASK_INFO"

ALTER TABLE "EASTANSY"."D_TASK_INFO" 
	ADD CONSTRAINT "PK_D_TASK_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."D_TASK_INFO"

CREATE INDEX "EASTANSY"."I_D_TASK_INFO_1" ON "EASTANSY"."D_TASK_INFO" 
		("MODEL_ID" ASC,
		 "SERVER_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."D_TASK_INFO"

CREATE INDEX "EASTANSY"."I_D_TASK_INFO_2" ON "EASTANSY"."D_TASK_INFO" 
		("USER_ID" ASC,
		 "RUN_STATE" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."D_TASK_PARMS"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."D_TASK_PARMS"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "TASK_ID" VARCHAR(50) , 
		  "PARM_ID" VARCHAR(50) , 
		  "PARM_VALUE" VARCHAR(2000) )   
		 IN "EASTSS" ; 

COMMENT ON TABLE "EASTANSY"."D_TASK_PARMS" IS '变量UUID 是变量表中的UUID，可以唯一区分变量的ID，不是变量Code';


-- 表上主键的 DDL 语句 "EASTANSY"."D_TASK_PARMS"

ALTER TABLE "EASTANSY"."D_TASK_PARMS" 
	ADD CONSTRAINT "PK_D_TASK_PARMS" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."D_TASK_PARMS"

CREATE INDEX "EASTANSY"."I_D_TASK_PARMS_1" ON "EASTANSY"."D_TASK_PARMS" 
		("TASK_ID" ASC,
		 "PARM_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_CHART_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_CHART_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODEID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "RESULT_TABLE" VARCHAR(100) , 
		  "CHART_TYPE" VARCHAR(1) , 
		  "X_COL" VARCHAR(50) , 
		  "Y_COL" VARCHAR(50) , 
		  "X_TABLE" VARCHAR(50) , 
		  "Y_TABLE" VARCHAR(50) , 
		  "GROUP_COL" VARCHAR(50) , 
		  "GROUP_TABLE" VARCHAR(50) , 
		  "Y_ANA_TYPE" VARCHAR(1) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_CHART_INFO"

ALTER TABLE "EASTANSY"."M_CHART_INFO" 
	ADD CONSTRAINT "PK_M_CHART_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_CHART_INFO"

CREATE INDEX "EASTANSY"."I_M_CHART_INFO_1" ON "EASTANSY"."M_CHART_INFO" 
		("JOB_ID" ASC,
		 "MODEL_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_COL_LABEL"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_COL_LABEL"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "SERVER_ID" VARCHAR(50) , 
		  "TABLE_NAME" VARCHAR(100) , 
		  "COL_NAME" VARCHAR(200) , 
		  "COL_LABEL" VARCHAR(500) , 
		  "SOURCE_TABLE_FLAG" VARCHAR(1) , 
		  "GLOBAL_FLAG" VARCHAR(1) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "SORT_CODE" INTEGER WITH DEFAULT 0 , 
		  "COLTYPE" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_COL_LABEL"

ALTER TABLE "EASTANSY"."M_COL_LABEL" 
	ADD CONSTRAINT "PK_M_COL_LABEL" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_COL_LABEL"

CREATE INDEX "EASTANSY"."I_M_COL_LABEL_1" ON "EASTANSY"."M_COL_LABEL" 
		("GLOBAL_FLAG" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."M_COL_LABEL"

CREATE INDEX "EASTANSY"."I_M_COL_LABEL_2" ON "EASTANSY"."M_COL_LABEL" 
		("TABLE_NAME" ASC,
		 "SERVER_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."M_COL_LABEL"

CREATE INDEX "EASTANSY"."I_M_COL_LABEL_3" ON "EASTANSY"."M_COL_LABEL" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_FREQ_ANA"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_FREQ_ANA"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SORT_CODE" INTEGER , 
		  "ANA_COL" VARCHAR(100) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "ANA_COL_TYPE" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_FREQ_ANA"

ALTER TABLE "EASTANSY"."M_FREQ_ANA" 
	ADD CONSTRAINT "PK_M_FREQ_ANA" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_FREQ_ANA"

CREATE INDEX "EASTANSY"."I_M_FREQ_ANA_1" ON "EASTANSY"."M_FREQ_ANA" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_FREQ_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_FREQ_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "RESULT_TABLE" VARCHAR(100) , 
		  "VIEW_FLAG" VARCHAR(1) , 
		  "NULL_SHOW_FLAG" VARCHAR(1) , 
		  "NULL_CAL_FLAG" VARCHAR(1) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_FREQ_INFO"

ALTER TABLE "EASTANSY"."M_FREQ_INFO" 
	ADD CONSTRAINT "PK_M_FREQ_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_FREQ_INFO"

CREATE INDEX "EASTANSY"."I_M_FREQ_INFO_1" ON "EASTANSY"."M_FREQ_INFO" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_JOB_NODE_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_JOB_NODE_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "NODE_NAME" VARCHAR(200) , 
		  "NODE_TYPE" VARCHAR(50) , 
		  "TASK_FLAG" VARCHAR(1) , 
		  "SQL_TEXT" VARCHAR(4000) , 
		  "SORT_CODE" INTEGER , 
		  "RESULT_FLAG" VARCHAR(1) , 
		  "DATA_TYPE" VARCHAR(1) , 
		  "SOURCE_TABLE_FLAG" VARCHAR(1) , 
		  "RESULT_DATA" VARCHAR(200) , 
		  "RESULT_LABEL" VARCHAR(2000) , 
		  "REMARK" VARCHAR(4000) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_JOB_NODE_INFO"

ALTER TABLE "EASTANSY"."M_JOB_NODE_INFO" 
	ADD CONSTRAINT "PK_M_JOB_NODE_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_JOB_NODE_INFO"

CREATE INDEX "EASTANSY"."I_M_JOB_NODE_INFO1" ON "EASTANSY"."M_JOB_NODE_INFO" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."M_JOB_NODE_INFO"

CREATE INDEX "EASTANSY"."I_M_JOB_NODE_INFO2" ON "EASTANSY"."M_JOB_NODE_INFO" 
		("TASK_FLAG" ASC,
		 "RESULT_FLAG" ASC,
		 "SORT_CODE" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_MODEL_TO_MY_TYPE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_MODEL_TO_MY_TYPE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "MODEL_ID" VARCHAR(50) , 
		  "TYPE_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_MODEL_TO_MY_TYPE"

ALTER TABLE "EASTANSY"."M_MODEL_TO_MY_TYPE" 
	ADD CONSTRAINT "PK_M_MODEL_TO_MY_TYPE" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_MODEL_TO_MY_TYPE"

CREATE INDEX "EASTANSY"."I_M_MODELTOMYTYPE1" ON "EASTANSY"."M_MODEL_TO_MY_TYPE" 
		("MODEL_ID" ASC,
		 "TYPE_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_MODEL_TO_PUBLISH_TYPE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_MODEL_TO_PUBLISH_TYPE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "MODEL_ID" VARCHAR(50) , 
		  "TYPE_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_MODEL_TO_PUBLISH_TYPE"

ALTER TABLE "EASTANSY"."M_MODEL_TO_PUBLISH_TYPE" 
	ADD CONSTRAINT "PK_M_MODEL_TO_PUBLISH_TYPE" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_MODEL_TO_PUBLISH_TYPE"

CREATE INDEX "EASTANSY"."I_M_MODEL_PUBLISH1" ON "EASTANSY"."M_MODEL_TO_PUBLISH_TYPE" 
		("MODEL_ID" ASC,
		 "TYPE_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_MY_TYPE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_MY_TYPE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "TYPE_NAME" VARCHAR(500) , 
		  "PARENT_ID" VARCHAR(50) , 
		  "REMARK" VARCHAR(2000) , 
		  "USERID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_MY_TYPE"

ALTER TABLE "EASTANSY"."M_MY_TYPE" 
	ADD CONSTRAINT "PK_M_MY_TYPE" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_MY_TYPE"

CREATE INDEX "EASTANSY"."I_M_MY_TYPE1" ON "EASTANSY"."M_MY_TYPE" 
		("USERID" ASC,
		 "PARENT_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_NODE_RELA"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_NODE_RELA"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "CUR_NODEID" VARCHAR(50) , 
		  "NEXT_NODEID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_NODE_RELA"

ALTER TABLE "EASTANSY"."M_NODE_RELA" 
	ADD CONSTRAINT "PK_M_NODE_RELA" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_NODE_RELA"

CREATE INDEX "EASTANSY"."I_M_NODE_RELA1" ON "EASTANSY"."M_NODE_RELA" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_PUBLISH_TYPE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_PUBLISH_TYPE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "TYPE_NAME" VARCHAR(500) , 
		  "PARENT_ID" VARCHAR(50) , 
		  "REMARK" VARCHAR(2000) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_PUBLISH_TYPE"

ALTER TABLE "EASTANSY"."M_PUBLISH_TYPE" 
	ADD CONSTRAINT "PK_M_PUBLISH_TYPE" PRIMARY KEY
		("UUID");


------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_GROUPBY"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_GROUPBY"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "GROUP_COL" VARCHAR(100) , 
		  "SORT_CODE" INTEGER , 
		  "TABLE_NICKNAME" VARCHAR(100) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_GROUPBY"

ALTER TABLE "EASTANSY"."M_Q_GROUPBY" 
	ADD CONSTRAINT "PK_M_Q_GROUPBY" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_GROUPBY"

CREATE INDEX "EASTANSY"."I_M_Q_GROUPBY1" ON "EASTANSY"."M_Q_GROUPBY" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_ORDER"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_ORDER"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "ORDER_COL" VARCHAR(100) , 
		  "ORDER_TYPE" VARCHAR(50) , 
		  "SORT_CODE" INTEGER , 
		  "TABLE_NICKNAME" VARCHAR(100) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_ORDER"

ALTER TABLE "EASTANSY"."M_Q_ORDER" 
	ADD CONSTRAINT "PK_M_Q_ORDER" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_ORDER"

CREATE INDEX "EASTANSY"."I_M_Q_ORDER1" ON "EASTANSY"."M_Q_ORDER" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_SELECT"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_SELECT"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "SELECT_COL" VARCHAR(100) , 
		  "SORT_CODE" INTEGER , 
		  "TTL_TYPE" VARCHAR(50) , 
		  "CAL_UUID" VARCHAR(50) , 
		  "COL_LABEL" VARCHAR(100) , 
		  "TABLE_NICKNAME" VARCHAR(100) , 
		  "TARGET_COL_NAME" VARCHAR(100) , 
		  "COLTYPE" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_SELECT"

ALTER TABLE "EASTANSY"."M_Q_SELECT" 
	ADD CONSTRAINT "PK_M_Q_SELECT" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_SELECT"

CREATE INDEX "EASTANSY"."I_M_Q_SELECT1" ON "EASTANSY"."M_Q_SELECT" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_TABLE_LABEL"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_TABLE_LABEL"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "SERVER_ID" VARCHAR(50) , 
		  "TABLE_NAME" VARCHAR(100) , 
		  "COL_LABEL" VARCHAR(500) , 
		  "SOURCE_TABLE_FLAG" VARCHAR(1) , 
		  "GLOBAL_FLAG" VARCHAR(1) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_TABLE_LABEL"

ALTER TABLE "EASTANSY"."M_TABLE_LABEL" 
	ADD CONSTRAINT "PK_M_TABLE_LABEL" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_TABLE_LABEL"

CREATE INDEX "EASTANSY"."I_M_TABLE_LABEL_1" ON "EASTANSY"."M_TABLE_LABEL" 
		("GLOBAL_FLAG" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."M_TABLE_LABEL"

CREATE INDEX "EASTANSY"."I_M_TABLE_LABEL2" ON "EASTANSY"."M_TABLE_LABEL" 
		("TABLE_NAME" ASC,
		 "SERVER_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."M_TABLE_LABEL"

CREATE INDEX "EASTANSY"."I_M_TABLE_LABEL3" ON "EASTANSY"."M_TABLE_LABEL" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_TTL_STATISTIC_ANA"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_TTL_STATISTIC_ANA"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SORT_CODE" INTEGER , 
		  "ANA_COL" VARCHAR(100) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "ANA_COL_TYPE" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_TTL_STATISTIC_ANA"

ALTER TABLE "EASTANSY"."M_TTL_STATISTIC_ANA" 
	ADD CONSTRAINT "PK_M_TTL_STATISTIC_ANA" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_TTL_STATISTIC_ANA"

CREATE INDEX "EASTANSY"."I_M_TTL_STATISTIC1" ON "EASTANSY"."M_TTL_STATISTIC_ANA" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_TTL_STATISTIC_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_TTL_STATISTIC_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SORT_CODE" INTEGER , 
		  "ANA_AVG" VARCHAR(1) , 
		  "ANA_SD" VARCHAR(1) , 
		  "ANA_SE" VARCHAR(1) , 
		  "ANA_V" VARCHAR(1) , 
		  "ANA_MAX" VARCHAR(1) , 
		  "ANA_MIN" VARCHAR(1) , 
		  "ANA_G" VARCHAR(1) , 
		  "ANA_SUM" VARCHAR(1) , 
		  "ANA_COUNT" VARCHAR(1) , 
		  "ANA_NULL_COUNT" VARCHAR(1) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_TTL_STATISTIC_INFO"

ALTER TABLE "EASTANSY"."M_TTL_STATISTIC_INFO" 
	ADD CONSTRAINT "PK_M_TTL_STATISTIC_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_TTL_STATISTIC_INFO"

CREATE INDEX "EASTANSY"."I_M_TTL_STATISTIC4" ON "EASTANSY"."M_TTL_STATISTIC_INFO" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_DEPT"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_DEPT"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "DEPT_NAME" VARCHAR(100) , 
		  "DEPT_FULLNAME" VARCHAR(200) , 
		  "DEPT_STATUS" VARCHAR(6) , 
		  "DEPT_LEVEL" VARCHAR(2) , 
		  "PARENT_ID" VARCHAR(50) , 
		  "SORT_CODE" INTEGER , 
		  "ORG_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_DEPT"

ALTER TABLE "EASTANSY"."RBAC_DEPT" 
	ADD CONSTRAINT "P_RBAC_DEPT_KEY1" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."RBAC_DEPT"

CREATE INDEX "EASTANSY"."I_RBAC_DEPT1" ON "EASTANSY"."RBAC_DEPT" 
		("SORT_CODE" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_GROUP"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_GROUP"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "GROUP_NAME" VARCHAR(500) , 
		  "PARENTID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_GROUP"

ALTER TABLE "EASTANSY"."RBAC_GROUP" 
	ADD CONSTRAINT "PK_RBAC_GROUP" PRIMARY KEY
		("UUID");


------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_GROUP_MODEL"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_GROUP_MODEL"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "GROUP_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_GROUP_MODEL"

ALTER TABLE "EASTANSY"."RBAC_GROUP_MODEL" 
	ADD CONSTRAINT "PK_RBAC_GROUP_MODEL" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."RBAC_GROUP_MODEL"

CREATE INDEX "EASTANSY"."I_RBAC_GROUP_MODEL" ON "EASTANSY"."RBAC_GROUP_MODEL" 
		("GROUP_ID" ASC,
		 "MODEL_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_GROUP_SERVER"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_GROUP_SERVER"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "GROUP_ID" VARCHAR(50) , 
		  "SERVER_ID" VARCHAR(50) , 
		  "ALL_TABLE_FLAG" VARCHAR(1) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_GROUP_SERVER"

ALTER TABLE "EASTANSY"."RBAC_GROUP_SERVER" 
	ADD CONSTRAINT "PK_RBAC_GROUP_SERVER" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."RBAC_GROUP_SERVER"

CREATE INDEX "EASTANSY"."I_RBAC_GROUP_SERVE" ON "EASTANSY"."RBAC_GROUP_SERVER" 
		("GROUP_ID" ASC,
		 "SERVER_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_RESOURCE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_RESOURCE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "RESOURCE_NAME" VARCHAR(100) , 
		  "PARENT_ID" VARCHAR(50) , 
		  "REMARK" VARCHAR(500) , 
		  "SORTCODE" INTEGER , 
		  "PARMS" VARCHAR(1000) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_RESOURCE"

ALTER TABLE "EASTANSY"."RBAC_RESOURCE" 
	ADD PRIMARY KEY
		("UUID");


------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_ROLE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_ROLE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "ROLE_NAME" VARCHAR(50) , 
		  "SORT_CODE" INTEGER )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_ROLE"

ALTER TABLE "EASTANSY"."RBAC_ROLE" 
	ADD PRIMARY KEY
		("UUID");


------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_ROLE_RESOURCE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_ROLE_RESOURCE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "ROLE_ID" VARCHAR(50) , 
		  "RESOURCE_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_ROLE_RESOURCE"

ALTER TABLE "EASTANSY"."RBAC_ROLE_RESOURCE" 
	ADD PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."RBAC_ROLE_RESOURCE"

CREATE INDEX "EASTANSY"."I_RBAC_ROLE_RESOUR" ON "EASTANSY"."RBAC_ROLE_RESOURCE" 
		("ROLE_ID" ASC,
		 "RESOURCE_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_SYSADMIN"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_SYSADMIN"  (
		  "USER_ID" VARCHAR(50) NOT NULL )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_SYSADMIN"

ALTER TABLE "EASTANSY"."RBAC_SYSADMIN" 
	ADD PRIMARY KEY
		("USER_ID");


------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_USER"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_USER"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "USER_CODE" VARCHAR(50) , 
		  "USER_NAME" VARCHAR(50) , 
		  "USER_FULLNAME" VARCHAR(100) , 
		  "DEPT_ID" VARCHAR(50) , 
		  "USER_STATUS" VARCHAR(8) , 
		  "PASSWORD" VARCHAR(50) , 
		  "SORT_CODE" INTEGER , 
		  "EMAIL" VARCHAR(50) , 
		  "MOBILE" VARCHAR(50) , 
		  "USER_KEY" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_USER"

ALTER TABLE "EASTANSY"."RBAC_USER" 
	ADD PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."RBAC_USER"

CREATE INDEX "EASTANSY"."I_RBAC_USER1" ON "EASTANSY"."RBAC_USER" 
		("DEPT_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_USER_GROUP"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_USER_GROUP"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "USER_ID" VARCHAR(50) , 
		  "GROUP_ID" VARCHAR(50) )   
		 IN "EASTSS" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_USER_GROUP"

ALTER TABLE "EASTANSY"."RBAC_USER_GROUP" 
	ADD CONSTRAINT "PK_RBAC_USER_GROUP" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."RBAC_USER_GROUP"

CREATE INDEX "EASTANSY"."I_RBAC_USER_GROUP1" ON "EASTANSY"."RBAC_USER_GROUP" 
		("GROUP_ID" ASC,
		 "USER_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."RBAC_USER_ROLE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."RBAC_USER_ROLE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "USER_ID" VARCHAR(50) , 
		  "ROLE_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."RBAC_USER_ROLE"

ALTER TABLE "EASTANSY"."RBAC_USER_ROLE" 
	ADD PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."RBAC_USER_ROLE"

CREATE INDEX "EASTANSY"."I_RBAC_USER_ROLE1" ON "EASTANSY"."RBAC_USER_ROLE" 
		("USER_ID" ASC,
		 "ROLE_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_MODEL_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_MODEL_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "MODEL_NAME" VARCHAR(500) , 
		  "MODEL_DESC" VARCHAR(4000) , 
		  "CREATE_USERID" VARCHAR(50) , 
		  "CREATE_USERNAME" VARCHAR(100) , 
		  "CREATE_TIME" TIMESTAMP , 
		  "UPDATE_USERID" VARCHAR(50) , 
		  "UPDATE_USERNAME" VARCHAR(100) , 
		  "UPDATE_TIME" TIMESTAMP , 
		  "PARM1" VARCHAR(4000) , 
		  "PARM2" VARCHAR(4000) , 
		  "PUBLISH_STATE" VARCHAR(1) , 
		  "PUBLISH_TIME" TIMESTAMP , 
		  "MODEL_PIC" CLOB(2097152) LOGGED NOT COMPACT , 
		  "IS_PUBLIC" VARCHAR(1) , 
		  "IS_MODEL_SHOW" VARCHAR(1) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_MODEL_INFO"

ALTER TABLE "EASTANSY"."M_MODEL_INFO" 
	ADD CONSTRAINT "PK_M_MODEL_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_MODEL_INFO"

CREATE INDEX "EASTANSY"."I_M_MODEL_INFO_1" ON "EASTANSY"."M_MODEL_INFO" 
		("CREATE_USERID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."M_MODEL_INFO"

CREATE INDEX "EASTANSY"."I_M_MODEL_INFO_2" ON "EASTANSY"."M_MODEL_INFO" 
		("PUBLISH_STATE" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."M_MODEL_INFO"

CREATE INDEX "EASTANSY"."I_M_MODEL_INFO_3" ON "EASTANSY"."M_MODEL_INFO" 
		("UPDATE_TIME" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "Q_TYPE" VARCHAR(1) , 
		  "DISTINCT_FLAG" VARCHAR(1) , 
		  "AUTOGROUPBY_FLAG" VARCHAR(1) )   
		 IN "EASTSS" ; 

COMMENT ON TABLE "EASTANSY"."M_Q_INFO" IS '查询类型 Q_TYPE 0：查询生成器 1：过滤和排序 是否过滤重复值	DISTINCT_FLAG 0：不过滤 1：过滤';


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_INFO"

ALTER TABLE "EASTANSY"."M_Q_INFO" 
	ADD CONSTRAINT "PK_M_Q_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_INFO"

CREATE INDEX "EASTANSY"."I_M_Q_INFO1" ON "EASTANSY"."M_Q_INFO" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_JOB_NODE_INDEX"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_JOB_NODE_INDEX"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "INDEX_ID" VARCHAR(50) , 
		  "INDEX_TABLE" VARCHAR(100) , 
		  "INDEX_COL" VARCHAR(100) , 
		  "INDEX_NAME" CHAR(200) )   
		 IN "EASTSS" ; 

COMMENT ON TABLE "EASTANSY"."M_JOB_NODE_INDEX" IS '本表主要用于索引管理 索引ID	INDEX_ID 相同的，为一组索引， 节点ID	NODE_ID 用于指定是在哪个节点上设置的索引 ，当节点使用视图时，本表中 该 节点ID 下的数据都应该清除';


-- 表上主键的 DDL 语句 "EASTANSY"."M_JOB_NODE_INDEX"

ALTER TABLE "EASTANSY"."M_JOB_NODE_INDEX" 
	ADD CONSTRAINT "PK_M_JOB_NODE_INDEX" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_JOB_NODE_INDEX"

CREATE INDEX "EASTANSY"."I_M_JOB_NODEINDEX1" ON "EASTANSY"."M_JOB_NODE_INDEX" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_DBSERVER_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_DBSERVER_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "DB_NAME" VARCHAR(100) , 
		  "SHOW_NAME" VARCHAR(1000) , 
		  "IP_ADRESS" VARCHAR(100) , 
		  "DB_PORT" VARCHAR(100) , 
		  "DB_USER" VARCHAR(100) , 
		  "DB_PWD" VARCHAR(100) , 
		  "USED_FLAG" VARCHAR(1) , 
		  "SOURCE_FLAG" VARCHAR(1) , 
		  "SCHEMA_NAME" VARCHAR(200) , 
		  "DATA_SPACE" VARCHAR(200) , 
		  "INDEX_SPACE" VARCHAR(200) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_DBSERVER_INFO"

ALTER TABLE "EASTANSY"."M_DBSERVER_INFO" 
	ADD CONSTRAINT "PK_M_DBSERVER_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_DBSERVER_INFO"

CREATE INDEX "EASTANSY"."I_M_DBSERVER_INFO1" ON "EASTANSY"."M_DBSERVER_INFO" 
		("DB_NAME" ASC,
		 "USED_FLAG" ASC,
		 "SOURCE_FLAG" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_MODEL_SHARE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_MODEL_SHARE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "MODEL_ID" VARCHAR(50) , 
		  "USER_ID" VARCHAR(50) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_MODEL_SHARE"

ALTER TABLE "EASTANSY"."M_MODEL_SHARE" 
	ADD CONSTRAINT "PK_M_MODEL_SHARE" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_MODEL_SHARE"

CREATE INDEX "EASTANSY"."I_M_MODEL_SHARE_1" ON "EASTANSY"."M_MODEL_SHARE" 
		("MODEL_ID" ASC,
		 "USER_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_JOBFLOW_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_JOBFLOW_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "MODEL_ID" VARCHAR(50) , 
		  "JOB_NAME" VARCHAR(500) , 
		  "CREATE_USERID" VARCHAR(50) , 
		  "CREATE_USERNAME" VARCHAR(100) , 
		  "CREATE_TIME" TIMESTAMP , 
		  "UPDATE_USERID" VARCHAR(50) , 
		  "UPDATE_USERNAME" VARCHAR(100) , 
		  "UPDATE_TIME" TIMESTAMP , 
		  "SORT_CODE" INTEGER , 
		  "FLOW_DATA" CLOB(2097152) LOGGED NOT COMPACT )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_JOBFLOW_INFO"

ALTER TABLE "EASTANSY"."M_JOBFLOW_INFO" 
	ADD CONSTRAINT "PK_M_JOBFLOW_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_JOBFLOW_INFO"

CREATE INDEX "EASTANSY"."I_M_JOBFLOW_INFO_1" ON "EASTANSY"."M_JOBFLOW_INFO" 
		("MODEL_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."D_TASK_SUBINFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."D_TASK_SUBINFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "TASK_ID" VARCHAR(50) , 
		  "NODE_ID" VARCHAR(50) , 
		  "RUN_STATE" VARCHAR(1) , 
		  "START_TIME" TIMESTAMP , 
		  "END_TIME" TIMESTAMP , 
		  "SQL_TEXT" VARCHAR(4000) , 
		  "SORT_CODE" INTEGER , 
		  "CREATE_TIME" TIMESTAMP , 
		  "DATA_TYPE" VARCHAR(1) , 
		  "RESULT_DATA" VARCHAR(200) , 
		  "NODE_NAME" VARCHAR(1000) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."D_TASK_SUBINFO"

ALTER TABLE "EASTANSY"."D_TASK_SUBINFO" 
	ADD CONSTRAINT "PK_D_TASK_SUBINFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."D_TASK_SUBINFO"

CREATE INDEX "EASTANSY"."I_D_TASK_SUBINFO_1" ON "EASTANSY"."D_TASK_SUBINFO" 
		("TASK_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;

-- 表上的索引的 DDL 语句 "EASTANSY"."D_TASK_SUBINFO"

CREATE INDEX "EASTANSY"."I_D_TASK_SUBINFO_2" ON "EASTANSY"."D_TASK_SUBINFO" 
		("RUN_STATE" ASC,
		 "SORT_CODE" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_MODEL_PARMS"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_MODEL_PARMS"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "MODEL_ID" VARCHAR(50) , 
		  "PARM_CODE" VARCHAR(50) , 
		  "PARM_NAME" VARCHAR(200) , 
		  "PARM_DESC" VARCHAR(200) , 
		  "PARM_TYPE" VARCHAR(1) , 
		  "DEFALT_VALUE" VARCHAR(2000) , 
		  "USERED_DESC" VARCHAR(2000) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_MODEL_PARMS"

ALTER TABLE "EASTANSY"."M_MODEL_PARMS" 
	ADD CONSTRAINT "PK_M_MODEL_PARMS" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_MODEL_PARMS"

CREATE INDEX "EASTANSY"."I_M_MODEL_PARMS_1" ON "EASTANSY"."M_MODEL_PARMS" 
		("MODEL_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_CALCOL"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_CALCOL"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "CAL_NAME" VARCHAR(200) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "SELECT_COL" VARCHAR(100) , 
		  "CAL_TYPE" VARCHAR(1) , 
		  "CAL_TEXT" VARCHAR(2000) , 
		  "WHEN_VALUE" VARCHAR(2000) , 
		  "THEN_VALUE" VARCHAR(2000) , 
		  "ELSE_VALUE" VARCHAR(2000) , 
		  "ELSE_TYPE" VARCHAR(50) , 
		  "DATA_FLAG" VARCHAR(1) , 
		  "TABLE_NICKNAME" VARCHAR(100) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_CALCOL"

ALTER TABLE "EASTANSY"."M_Q_CALCOL" 
	ADD CONSTRAINT "PK_M_Q_CALCOL" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_CALCOL"

CREATE INDEX "EASTANSY"."I_M_Q_CALCOL1" ON "EASTANSY"."M_Q_CALCOL" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_WHERE"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_WHERE"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "WHERE_COL" VARCHAR(100) , 
		  "COMP_TYPE" VARCHAR(50) , 
		  "WHERE_VALUE" VARCHAR(1000) , 
		  "WHERE_VALUE_TYPE" VARCHAR(1) , 
		  "BETWEEN_VALUE" VARCHAR(1000) , 
		  "BETWEEN_VALUE_TYPE" VARCHAR(1) , 
		  "DATA_FLAG" VARCHAR(1) , 
		  "SORT_CODE" INTEGER , 
		  "TYPE_FLAG" VARCHAR(1) , 
		  "SUPER_FLAG" VARCHAR(1) , 
		  "TABLE_NICKNAME" VARCHAR(100) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_WHERE"

ALTER TABLE "EASTANSY"."M_Q_WHERE" 
	ADD CONSTRAINT "PK_M_Q_WHERE" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_WHERE"

CREATE INDEX "EASTANSY"."I_M_Q_WHERE1" ON "EASTANSY"."M_Q_WHERE" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_HAVING"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_HAVING"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "HAVING_COL" VARCHAR(100) , 
		  "COMP_TYPE" VARCHAR(50) , 
		  "HAVING_VALUE" VARCHAR(1000) , 
		  "HAVING_VALUE_TYPE" VARCHAR(1) , 
		  "BETWEEN_VALUE" VARCHAR(1000) , 
		  "BETWEEN_VALUE_TYPE" VARCHAR(1) , 
		  "DATA_FLAG" VARCHAR(1) , 
		  "SORT_CODE" INTEGER , 
		  "TYPE_FLAG" VARCHAR(1) , 
		  "SUPER_FLAG" VARCHAR(1) , 
		  "TABLE_NICKNAME" VARCHAR(100) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_HAVING"

ALTER TABLE "EASTANSY"."M_Q_HAVING" 
	ADD CONSTRAINT "M_Q_HAVING" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_HAVING"

CREATE INDEX "EASTANSY"."I_M_Q_HAVING1" ON "EASTANSY"."M_Q_HAVING" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_Q_JOIN"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_Q_JOIN"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "TABLEA" VARCHAR(100) , 
		  "NICK_NAMEA" VARCHAR(100) , 
		  "TABLEA_COL" VARCHAR(100) , 
		  "TABLEB" VARCHAR(50) , 
		  "NICK_NAMEB" VARCHAR(100) , 
		  "TABLEB_COL" VARCHAR(100) , 
		  "JOIN_TYPE" VARCHAR(1) , 
		  "COMP_TYPE" VARCHAR(50) , 
		  "SORT_CODE" VARCHAR(500) )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_Q_JOIN"

ALTER TABLE "EASTANSY"."M_Q_JOIN" 
	ADD CONSTRAINT "PK_M_Q_JOIN" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_Q_JOIN"

CREATE INDEX "EASTANSY"."I_M_Q_JOIN1" ON "EASTANSY"."M_Q_JOIN" 
		("MODEL_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."M_APPEND_TAB_INFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."M_APPEND_TAB_INFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "NODE_ID" VARCHAR(50) , 
		  "JOB_ID" VARCHAR(50) , 
		  "MODEL_ID" VARCHAR(50) , 
		  "SOURCE_TABLE" VARCHAR(100) , 
		  "UNION_TYPE" VARCHAR(1) , 
		  "SOURCE_TABLE_FLAG" VARCHAR(1) , 
		  "TABLE_NICKNAME" VARCHAR(100) , 
		  "SORT_CODE" INTEGER )   
		 IN "EASTSS" INDEX IN "EASTSSI" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."M_APPEND_TAB_INFO"

ALTER TABLE "EASTANSY"."M_APPEND_TAB_INFO" 
	ADD CONSTRAINT "PK_M_APPEND_TAB_INFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."M_APPEND_TAB_INFO"

CREATE INDEX "EASTANSY"."I_M_APPENDTABINFO1" ON "EASTANSY"."M_APPEND_TAB_INFO" 
		("NODE_ID" ASC,
		 "JOB_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."D_TASK_RUN_ERRORINFO"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."D_TASK_RUN_ERRORINFO"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "TASK_ID" VARCHAR(50) , 
		  "SUBTASK_ID" VARCHAR(50) , 
		  "ERRORINFO" CLOB(1048576) LOGGED NOT COMPACT , 
		  "ERROR_TYPE" VARCHAR(10) , 
		  "SERVER_NAME" VARCHAR(200) , 
		  "NODE_NAME" VARCHAR(1000) , 
		  "MODEL_NAME" VARCHAR(500) )   
		 IN "EASTSS" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."D_TASK_RUN_ERRORINFO"

ALTER TABLE "EASTANSY"."D_TASK_RUN_ERRORINFO" 
	ADD CONSTRAINT "PK_D_TASK_RUN_ERRORINFO" PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."D_TASK_RUN_ERRORINFO"

CREATE INDEX "EASTANSY"."I_DTASK_RUN_ERROR1" ON "EASTANSY"."D_TASK_RUN_ERRORINFO" 
		("TASK_ID" ASC,
		 "SUBTASK_ID" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;
------------------------------------------------
-- 表的 DDL 语句 "EASTANSY"."D_TABLE_ROWCOUNT"
------------------------------------------------
 

CREATE TABLE "EASTANSY"."D_TABLE_ROWCOUNT"  (
		  "UUID" VARCHAR(50) NOT NULL , 
		  "SERVER_ID" VARCHAR(100) , 
		  "TABLE_NAME" VARCHAR(100) , 
		  "ROW_COUNT" INTEGER )   
		 IN "EASTSS" ; 


-- 表上主键的 DDL 语句 "EASTANSY"."D_TABLE_ROWCOUNT"

ALTER TABLE "EASTANSY"."D_TABLE_ROWCOUNT" 
	ADD PRIMARY KEY
		("UUID");



-- 表上的索引的 DDL 语句 "EASTANSY"."D_TABLE_ROWCOUNT"

CREATE INDEX "EASTANSY"."I_DTABLE_ROWCOUNT1" ON "EASTANSY"."D_TABLE_ROWCOUNT" 
		("SERVER_ID" ASC,
		 "TABLE_NAME" ASC)
		PCTFREE 10 DISALLOW REVERSE SCANS;







---------------------------------
-- 存储过程的 DDL 语句
---------------------------------


SET CURRENT SCHEMA = "EASTANSY";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","EASTANSY";
create procedure EAST.PRO_CURSOR(IN TABLENAME VARCHAR(100),IN CURSORNAME
VARCHAR(100))
 DYNAMIC RESULT SETS 1
 LANGUAGE SQL
 begin
 declare sqlStr varchar(1024);--
 declare stmr statement;--
 declare cursorName cursor with return to client for stmt;--
 set sqlStr = 'select * from '|| tableName||' with ur';--
 prepare stmt from sqlStr;--
 open cursorName;--
 end;

GRANT CONNECT ON DATABASE TO USER "EASTANSY";

GRANT CREATETAB ON DATABASE TO USER "EASTANSY";

GRANT IMPLICIT_SCHEMA ON DATABASE TO USER "EASTANSY";

GRANT BINDADD ON DATABASE TO USER "EASTANSY";

GRANT CREATE_NOT_FENCED_ROUTINE ON DATABASE TO USER "EASTANSY";

GRANT LOAD ON DATABASE TO USER "EASTANSY";

GRANT CREATE_EXTERNAL_ROUTINE ON DATABASE TO USER "EASTANSY";

GRANT QUIESCE_CONNECT ON DATABASE TO USER "EASTANSY";

GRANT USE OF TABLESPACE "EASTSS" TO USER "EASTANSY" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "EASTSSI" TO USER "EASTANSY" WITH GRANT OPTION;

GRANT CONTROL ON TABLE "EASTANSY"."D_EVENTLOG" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."D_TABLE_ROWCOUNT" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."D_TASK_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."D_TASK_PARMS" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."D_TASK_RUN_ERRORINFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."D_TASK_SUBINFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_APPEND_TAB_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_CHART_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_COL_LABEL" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_DBSERVER_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_FREQ_ANA" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_FREQ_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_JOB_NODE_INDEX" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_JOB_NODE_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_JOBFLOW_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_MODEL_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_MODEL_PARMS" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_MODEL_SHARE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_MODEL_TO_MY_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_MODEL_TO_PUBLISH_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_MY_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_NODE_RELA" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_PUBLISH_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_CALCOL" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_GROUPBY" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_HAVING" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_JOIN" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_ORDER" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_SELECT" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_Q_WHERE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_TABLE_LABEL" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_TTL_STATISTIC_ANA" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."M_TTL_STATISTIC_INFO" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_DEPT" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_GROUP" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_GROUP_MODEL" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_GROUP_SERVER" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_RESOURCE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_ROLE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_ROLE_RESOURCE" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_SYSADMIN" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_USER" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_USER_GROUP" TO USER "EASTANSY";

GRANT CONTROL ON TABLE "EASTANSY"."RBAC_USER_ROLE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_D_EVENTLOG_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_D_EVENTLOG_2" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_D_TASK_INFO_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_D_TASK_INFO_2" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_D_TASK_PARMS_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_D_TASK_SUBINFO_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_D_TASK_SUBINFO_2" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_DTABLE_ROWCOUNT1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_DTASK_RUN_ERROR1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_APPENDTABINFO1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_CHART_INFO_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_COL_LABEL_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_COL_LABEL_2" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_COL_LABEL_3" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_DBSERVER_INFO1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_FREQ_ANA_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_FREQ_INFO_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_JOB_NODE_INFO1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_JOB_NODE_INFO2" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_JOB_NODEINDEX1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_JOBFLOW_INFO_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MODEL_INFO_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MODEL_INFO_2" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MODEL_INFO_3" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MODEL_PARMS_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MODEL_PUBLISH1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MODEL_SHARE_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MODELTOMYTYPE1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_MY_TYPE1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_NODE_RELA1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_CALCOL1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_GROUPBY1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_HAVING1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_INFO1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_JOIN1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_ORDER1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_SELECT1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_Q_WHERE1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_TABLE_LABEL_1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_TABLE_LABEL2" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_TABLE_LABEL3" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_TTL_STATISTIC1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_M_TTL_STATISTIC4" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_RBAC_DEPT1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_RBAC_GROUP_MODEL" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_RBAC_GROUP_SERVE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_RBAC_ROLE_RESOUR" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_RBAC_USER_GROUP1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_RBAC_USER_ROLE1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."I_RBAC_USER1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."M_Q_HAVING" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."P_RBAC_DEPT_KEY1" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_D_EVENTLOG" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_D_TASK_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_D_TASK_PARMS" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_D_TASK_RUN_ERRORINFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_D_TASK_SUBINFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_APPEND_TAB_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_CHART_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_COL_LABEL" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_DBSERVER_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_FREQ_ANA" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_FREQ_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_JOB_NODE_INDEX" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_JOB_NODE_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_JOBFLOW_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_MODEL_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_MODEL_PARMS" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_MODEL_SHARE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_MODEL_TO_MY_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_MODEL_TO_PUBLISH_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_MY_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_NODE_RELA" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_PUBLISH_TYPE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_Q_CALCOL" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_Q_GROUPBY" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_Q_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_Q_JOIN" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_Q_ORDER" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_Q_SELECT" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_Q_WHERE" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_TABLE_LABEL" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_TTL_STATISTIC_ANA" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_M_TTL_STATISTIC_INFO" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_RBAC_GROUP" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_RBAC_GROUP_MODEL" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_RBAC_GROUP_SERVER" TO USER "EASTANSY";

GRANT CONTROL ON INDEX "EASTANSY"."PK_RBAC_USER_GROUP" TO USER "EASTANSY";




COMMIT WORK;

CONNECT RESET;

TERMINATE;

