
CONNECT TO EASTST;

------------------------------------
-- BUFFERPOOLS 的 DDL 语句 --
------------------------------------
 
CREATE BUFFERPOOL "EASTRUN32K" SIZE AUTOMATIC PAGESIZE 32768;

CREATE BUFFERPOOL "EASTBUF32K" SIZE AUTOMATIC PAGESIZE 32768;

CREATE BUFFERPOOL "EAST1BUF32K" SIZE AUTOMATIC PAGESIZE 32768;

CREATE BUFFERPOOL "EAST2BUF32K" SIZE AUTOMATIC PAGESIZE 32768;

CREATE BUFFERPOOL "EAST3BUF32K" SIZE AUTOMATIC PAGESIZE 32768;

CREATE BUFFERPOOL "EAST4BUF32K" SIZE AUTOMATIC PAGESIZE 32768;

CREATE BUFFERPOOL "EAST5BUF32K"  SIZE AUTOMATIC PAGESIZE 32768;


------------------------------------
-- TABLESPACES 的 DDL 语句 --
------------------------------------


CREATE LARGE TABLESPACE "EASTRUNDATA" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 2 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EASTRUN32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;



CREATE LARGE TABLESPACE "EASTSS1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST1BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "EASTSS2" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST3BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "EASTINDEX" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EASTBUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE TEMPORARY TABLESPACE "TEMPSPACE2" IN DATABASE PARTITION GROUP IBMTEMPGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST5BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF;


CREATE LARGE TABLESPACE "ZZKJTSS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST2BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "GRDHQTSS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST2BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "GRXDTSS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST2BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "DGTSS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST2BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "ZCFZTSS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST2BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "JYLSTSS1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "JYLSTSS2" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "JYLSTSS3" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "JYLSTSS4" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "NBFZMX1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "NBFZMX2" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "NBFZMX3" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "NBFZMX4" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 1 G 
	 MAXSIZE NONE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST4BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE TEMPORARY TABLESPACE "TEMPSPACE3" IN DATABASE PARTITION GROUP IBMTEMPGROUP 
	 PAGESIZE 32768 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 64
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL EAST5BUF32K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF;


----------------------------------------
-- 数据库上的权限语句 
----------------------------------------

GRANT DBADM ON DATABASE TO USER "EASTST";

---------------------------------------
-- 表空间上的授权语句 
---------------------------------------
 

GRANT USE OF TABLESPACE "EASTRUNDATA" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "DGTSS" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "EASTINDEX" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "EASTSS1" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "EASTSS2" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "GRDHQTSS" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "GRXDTSS" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS1" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS2" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS3" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS4" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX1" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX2" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX3" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX4" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "ZCFZTSS" TO USER "EASTST" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "ZZKJTSS" TO USER "EASTST" WITH GRANT OPTION;
