-- 表/视图上的权限语句 
--------------------------------------------

 
GRANT CONTROL ON TABLE "GZYH"."T_GX_GWXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_GX_GWXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_GX_GYB" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_GX_GYB" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_GX_JGXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_GX_JGXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_GX_YGB" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_GX_YGB" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_JL_JYLS" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_JL_JYLS" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_BWYWMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_BWYWMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_DKMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_DKMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_GDJGL" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_GDJGL" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_KHJBXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KFX_KHJBXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_DGKHXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_DGKHXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GDXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GDXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GLGX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GLGX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GRJCXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GRJCXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GRKHGXXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KH_GRKHGXXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGDCFZ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGDCFZ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGDCFZMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGDCFZMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGHCFZ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGHCFZ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGHCFZMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGHCFZMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGXFZ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGXFZ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGXFZMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_DGXFZMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRDCFZ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRDCFZ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRDCFZMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRDCFZMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRHCFZ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRHCFZ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRHCFZMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRHCFZMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRXFZ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRXFZ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRXFZMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_GRXFZMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_NBFZ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_NBFZ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_NBKMKJ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_NBKMKJ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_TJKMKJ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_TJKMKJ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_ZZQKM" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_ZZQKM" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_CZXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_CZXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_JJKXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_JJKXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_XYKXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_XYKXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_XYKZJYMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KP_XYKZJYMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_BHYWXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_BHYWXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_DGBSY" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_DGBSY" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_DXYJJ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_DXYJJ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_GXYJJ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_GXYJJ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_MYRZYXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_MYRZYXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_PJPMXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_PJPMXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_WTDK" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_WTDK" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XDHT" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XDHT" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XMDKXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XMDKXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XYDGX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XYDGX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XYDHT" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XYDHT" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XYZDYW" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_XYZDYW" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_YTDK" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_SJD_YTDK" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DHJCB" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DHJCB" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DKHX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DKHX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DKWXB" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_NBFZMX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_NBFZMX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DKWXB" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DKZQ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_DKZQ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_SXXX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_SXXX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_XDZCZR" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_XDZCZR" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_ZZRGX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_XG_ZZRGX" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_ZFSN_SNTJ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_ZFSN_SNTJ" TO USER "GZYH" ;

GRANT CONTROL ON TABLE "GZYH"."T_ZFSN_ZFKTJ" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_ZFSN_ZFKTJ" TO USER "GZYH" ;

---------------------------------------
-- 模式上的权限语句 
---------------------------------------

 
GRANT CREATEIN ON SCHEMA "GZYH" TO USER "GZYH" ;

GRANT DROPIN ON SCHEMA "GZYH" TO USER "GZYH" ;

GRANT ALTERIN ON SCHEMA "GZYH" TO USER "GZYH" ;

---------------------------------------
-- 索引上的权限语句 
---------------------------------------

 
GRANT CONTROL ON INDEX "GZYH"."T_GX_GWXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_GYB" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_JGXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_YGB" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_YGB_SFZH" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_BWYWMX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_DKMX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_GDJGL" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_KHJBXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_DGKHXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_DGKHXX_FRDBZJHM" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GDXX_GDZJHM" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GLGX_KHSBM" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GRJCXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GRJCXX_ZJHM" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_DGDCFZ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_DGHCFZ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_DGXFZ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_GRDCFZ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_GRHCFZ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_GRXFZ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_NBFZ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_CZXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_CZXX_ZJHM" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_XYKXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_XYKXX_ZJHM" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_DXYJJ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_GXYJJ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_XDHT" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_YTDK" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_DHJCB" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_DKZQ" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_SXXX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_XDZCZR" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_ZZRGX" TO USER "EASTST" ;

GRANT CONTROL ON TABLE "GZYH"."T_KJ_NBFZMX" TO USER "EASTST" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_GWXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_GYB" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_JGXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_YGB" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_GX_YGB_SFZH" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_BWYWMX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_DKMX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_GDJGL" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KFX_KHJBXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_DGKHXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_DGKHXX_FRDBZJHM" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GDXX_GDZJHM" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GLGX_KHSBM" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GRJCXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KH_GRJCXX_ZJHM" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_DGDCFZ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_DGHCFZ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_DGXFZ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_GRDCFZ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_GRHCFZ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_GRXFZ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_NBFZ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_CZXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_CZXX_ZJHM" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_XYKXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KP_XYKXX_ZJHM" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_DXYJJ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_GXYJJ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_XDHT" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_SJD_YTDK" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_DHJCB" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_DKZQ" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_SXXX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_XDZCZR" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_XG_ZZRGX" TO USER "GZYH" ;

GRANT CONTROL ON INDEX "GZYH"."T_KJ_NBFZMX" TO USER "GZYH" ;
----------------------------------------
-- 数据库上的权限语句 
----------------------------------------


GRANT CREATETAB ON DATABASE  TO USER "GZYH" ;

GRANT BINDADD ON DATABASE  TO USER "GZYH" ;

GRANT CONNECT ON DATABASE  TO USER "GZYH" ;

GRANT CREATE_NOT_FENCED ON DATABASE  TO USER "GZYH" ;

GRANT IMPLICIT_SCHEMA ON DATABASE  TO USER "GZYH" ;

GRANT LOAD ON DATABASE  TO USER "GZYH" ;

GRANT QUIESCE_CONNECT ON DATABASE  TO USER "GZYH" ;


GRANT USE OF TABLESPACE "EASTRUNDATA" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "DGTSS" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "EASTINDEX" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "EASTSS1" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "EASTSS2" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "GRDHQTSS" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "GRXDTSS" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS1" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS2" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS3" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "JYLSTSS4" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX1" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX2" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX3" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "NBFZMX4" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "SYSTOOLSPACE" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "SYSTOOLSTMPSPACE" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "ZCFZTSS" TO USER "GZYH" WITH GRANT OPTION;

GRANT USE OF TABLESPACE "ZZKJTSS" TO USER "GZYH" WITH GRANT OPTION;



